services:
  db:
    image: postgres:16.1-alpine
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:6.2.6-alpine
    volumes:
      - redis_data:/data
    ports:
      - 26379:6379

  celery-worker:
    depends_on:
      - db
      - redis
    build: 
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./:/billing_backend
    env_file: ./.env
    working_dir: /billing_backend
    command: uv run python -m celery -A subscription_billing worker -l info

  celery-beat:
    depends_on:
      - db
      - redis
    build: 
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./:/billing_backend
    env_file: ./.env
    working_dir: /billing_backend
    command: uv run python -m celery -A subscription_billing beat -l info

  web:
    depends_on:
      - db
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./:/billing_backend
    env_file: ./.env
    working_dir: /billing_backend
    command: uv run python manage.py runserver 0.0.0.0:8000
    ports:
      - '8000:8000'

volumes:
  pg_data:
  static_volume:
  web_media_data:
  redis_data: