# Generated by Django 5.2.1 on 2025-05-30 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_setup_plans'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='currency',
            field=models.TextField(default='usd'),
        ),
        migrations.AddField(
            model_name='plan',
            name='currency',
            field=models.TextField(default='usd'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
