# Generated by Django 5.2.1 on 2025-05-31 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_invoice_subscription_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='next_billing_date',
        ),
        migrations.AddField(
            model_name='plan',
            name='integration_info',
            field=models.JSONField(default='{}'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.TextField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('overdue', 'Overdue')], default='pending'),
        ),
    ]
