# Generated by Django 5.2.1 on 2025-05-31 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_subscription_next_billing_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='integration_info',
            field=models.JSONField(default=dict),
        ),
    ]
